routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function() {

	Route::namespace('Auth')->middleware('guest:admin')->group(function() {
		Route::get('login', 'LoginController@showLoginForm')->name('login');
		Route::post('login', 'LoginController@login')->name('login');

	});

	Route::middleware('auth:admin')->group(function() {
		Route::get('', 'DashboardController@index')->name('dashboard');

		Route::namespace('Auth')->group(function() {
			Route::get('logout', 'LoginController@logout')->name('logout');
		});

		Route::namespace('Admins')->group(function() {
			Route::get('admin', 'AdminController@index')->name('admins.index');
			Route::get('admin/{id}', 'AdminController@show')->name('admins.show');
			Route::get('admin/{id}/edit', 'AdminController@edit')->name('admins.edit');
			Route::post('admin/{id}', 'AdminController@update')->name('admins.update');
			Route::delete('admin/{id}', 'AdminController@destroy')->name('admins.destroy');
		});

		Route::namespace('Users')->group(function() {
			Route::get('users', 'UserController@index')->name('users.index');
			Route::get('user/{id}', 'UserController@show')->name('users.show');
			Route::get('user/{id}/edit', 'UserController@edit')->name('users.edit');
			Route::post('user/{id}', 'UserController@update')->name('users.update');
			Route::delete('user/{id}', 'UserController@destroy')->name('users.destroy');
		});

		Route::namespace('ActivityLogs')->group(function() {
			Route::get('activity_logs', 'ActivityLogController@index')->name('activity_logs.index');
		});
	});


});

resources/views/admin/pages/admins/edit.blade.php
@extends('admin.layouts.master')

@section('breadcrumb')
	<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark font-weight-bold">Edit Admin</h1>
			</div><!-- /.col -->

			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="{{ route('admin.admins.index') }}">Admins</a></li>
						<li class="breadcrumb-item active">Edit</li>
				</ol>
			</div><!-- /.col -->
	</div><!-- /.row -->
	<hr>
@endsection

@section('content')
	<div class="content">
		<div class="container-fluid">
			<h3 class="mb-3">Admin Details</h3>					

			<form action="{{ route('admin.admins.update', $admin->id) }}" method="POST">
				@csrf
				<div class="row">
					<div class="form-group col-md-6">
						<label for="last_name">Last Name</label>
						<input type="text" class="form-control" name="last_name" value="{{ $admin->renderLastName() }}" required>
					</div>

					<div class="form-group col-md-6">
						<label for="first_name">First Name</label>
						<input type="text" class="form-control" name="first_name" value="{{ $admin->renderFirstName() }}" required>
					</div>	

					<div class="form-group col-md-6">
						<label for="email">Email</label>
						<input type="email" name="email" class="form-control" value="{{ $admin->renderEmail() }}" required>
					</div>
				</div>
				
				<button class="btn btn-primary">Update</button>
			</form>		
		</div>
	</div>
@endsection

resources/views/admin/pages/admins/index.blade.php
@extends('admin.layouts.master')

@section('breadcrumb')
	<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark font-weight-bold">Admins Index</h1>
			</div><!-- /.col -->

			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="{{ route('admin.admins.index') }}">Admins</a></li>
						<li class="breadcrumb-item active">Index</li>
				</ol>
			</div><!-- /.col -->
	</div><!-- /.row -->
	<hr>
@endsection

@section('content')
	<div class="content">
		<div class="container-fluid">
			
			<h3 class="mb-3">List of Admins</h3>

			<table id="dataTable" class="table table-striped table-bordered">
				<thead>
					<tr class="text-center">
						<th>ID</th>
						<th>Avatar</th>
						<th>Last Name</th>
						<th>First Name</th>
						<th>Email</th>
						<th>Status</th>
						<th>Action</th>
					</tr>
				</thead>

				<tbody>
					@foreach ($admins as $admin)
						<tr class="text-center">
							<td>{{ $admin->renderId() }}</td>
							<td><img src="{{ $admin->renderDisplayImage() }}" alt="Admin Image" width="50px" height="50px"></td>
							<td>{{ $admin->renderLastName() }}</td>
							<td>{{ $admin->renderFirstName() }}</td>
							<td>{{ $admin->renderEmail() }}</td>
							<td>{{ $admin->renderStatus() }}</td>
							<td class="d-flex justify-content-center">
								<a href="{{ route('admin.admins.show', $admin->id) }}" class="btn btn-primary mx-1">
									<i class="fas fa-eye"></i>
								</a>
								<a href="{{ route('admin.admins.edit', $admin->id) }}" class="btn btn-primary mx-1">
									<i class="fas fa-edit"></i>
								</a>

								<form class="deleteItem mx-1" action="{{ route('admin.admins.destroy', $admin->id) }}" method="POST">
									@csrf
									{{ method_field('DELETE') }}

									<button class="btn btn-danger"><i class="fas fa-trash"></i></button>
								</form>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>
@endsection

resources/views/admin/pages/admins/show.blade.php
@extends('admin.layouts.master')

@section('breadcrumb')
	<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark font-weight-bold">Show Admin</h1>
			</div><!-- /.col -->

			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="{{ route('admin.admins.index') }}">Admins</a></li>
						<li class="breadcrumb-item active">Show</li>
				</ol>
			</div><!-- /.col -->
	</div><!-- /.row -->
	<hr>
@endsection

@section('content')
	<div class="content">
		<div class="container-fluid">
			<div class="d-flex mb-3">
				<a href="{{ route('admin.admins.edit', $admin->id) }}" class="btn btn-primary mr-1">
					<i class="fas fa-edit"></i>
					Edit
				</a>	
				
		        <div>
		            <form class="deleteItem" action="{{ route('admin.admins.destroy', $admin->id) }}" method="POST">
		            	@csrf
		            	{{ method_field('DELETE') }}

		            	<button class="btn btn-danger"><i class="fas fa-trash mr-1"></i>Delete</button>
		            </form>
		        </div>
		    </div>

		    <div class="row">
		        <div class="col-md-12">
		            <div class="box">
		                <div class="box-header mb-3">
		                    <h3 class="box-title">Admin Details</h3>
		                </div>

		                <div class="box-body">
		                    <div class="row">
		                    	<div class="form-group col-md-6">
		                            <label for="email">ID</label>
		                            <p>{{ $admin->renderId() }}</p>
		                        </div>

		                        <div class="form-group col-md-6">
		                            <label for="email">Email</label>
		                            <p>{{ $admin->renderEmail() }}</p>
		                        </div>

		                        <div class="form-group col-md-6">
		                            <label for="lastName">Last Name</label>
		                            <p>{{ $admin->renderLastName() }}</p>
		                        </div>

		                        <div class="form-group col-md-6">
		                            <label for="firstName">First Name</label>
		                            <p>{{ $admin->renderFirstName() }}</p>
		                        </div>

		                        <div class="form-group col-md-6">
		                            <label for="status">Status</label>
		                            <p>{{ $admin->renderStatus() }}</p>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </div>
		    </div>
		</div>
	</div>
@endsection