routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function() {

	Route::namespace('Auth')->middleware('guest:admin')->group(function() {
		Route::get('login', 'LoginController@showLoginForm')->name('login');
		Route::post('login', 'LoginController@login')->name('login');

	});

	Route::middleware('auth:admin')->group(function() {
		Route::get('', 'DashboardController@index')->name('dashboard');

		Route::namespace('Auth')->group(function() {
			Route::get('logout', 'LoginController@logout')->name('logout');
		});

		Route::namespace('Admins')->group(function() {
			Route::get('admin', 'AdminController@index')->name('admins.index');
			Route::get('admin/{id}', 'AdminController@show')->name('admins.show');
			Route::get('admin/{id}/edit', 'AdminController@edit')->name('admins.edit');
			Route::post('admin/{id}', 'AdminController@update')->name('admins.update');
			Route::delete('admin/{id}', 'AdminController@destroy')->name('admins.destroy');
		});

		Route::namespace('Users')->group(function() {
			Route::get('users', 'UserController@index')->name('users.index');
			Route::get('user/{id}', 'UserController@show')->name('users.show');
			Route::get('user/{id}/edit', 'UserController@edit')->name('users.edit');
			Route::post('user/{id}', 'UserController@update')->name('users.update');
			Route::delete('user/{id}', 'UserController@destroy')->name('users.destroy');
		});

		Route::namespace('ActivityLogs')->group(function() {
			Route::get('activity_logs', 'ActivityLogController@index')->name('activity_logs.index');
		});
	});


});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'last_name', 'first_name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /** Renders */
    public function renderId()
    {
        return $this->id;
    }

    public function renderLastName()
    {
        return $this->last_name;
    }

    public function renderFirstName()
    {
        return $this->first_name;
    }

    public function renderFullName()
    {
        return $this->first_name. ' ' .$this->last_name;
    }

    public function renderEmail()
    {
        return $this->email;
    }

    public function renderDisplayImage()
    {
        if ($this->image_path) {
            return '/storage/' .$this->image_path;
        }

        return '/storage/no-image.jpg';
    }
}

app/Http/Controllers/Admin/Users/UserController.php
<?php

namespace App\Http\Controllers\Admin\Users;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return view('admin.pages.users.index', [
            'users' => $users,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);

        return view('admin.pages.users.show', [
            'user' => $user,
        ]);   
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);

        return view('admin.pages.users.edit', [
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $vars = $request->only(['last_name', 'first_name', 'email']);
        $user = User::find($id);
        $user->update($vars);

        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);

        $user->delete();

        return redirect()->route('admin.users.index');
    }
}

resources/views/admin/pages/users/edit.blade.php
@extends('admin.layouts.master')

@section('breadcrumb')
	<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark font-weight-bold">Edit Admin</h1>
			</div><!-- /.col -->

			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}">Users</a></li>
						<li class="breadcrumb-item active">Edit</li>
				</ol>
			</div><!-- /.col -->
	</div><!-- /.row -->
	<hr>
@endsection

@section('content')
	<div class="content">
		<div class="container-fluid">
			<h3 class="mb-3">User Details</h3>					

			<form action="{{ route('admin.users.update', $user->id) }}" method="POST">
				@csrf
				<div class="row">
					<div class="form-group col-md-6">
						<label for="last_name">Last Name</label>
						<input type="text" class="form-control" name="last_name" value="{{ $user->renderLastName() }}" required>
					</div>

					<div class="form-group col-md-6">
						<label for="first_name">First Name</label>
						<input type="text" class="form-control" name="first_name" value="{{ $user->renderFirstName() }}" required>
					</div>	

					<div class="form-group col-md-6">
						<label for="email">Email</label>
						<input type="email" name="email" class="form-control" value="{{ $user->renderEmail() }}" required>
					</div>
				</div>
				
				<button class="btn btn-primary">Update</button>
			</form>		
		</div>
	</div>
@endsection

resources/views/admin/pages/users/index.blade.php
@extends('admin.layouts.master')

@section('breadcrumb')
	<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark font-weight-bold">Users Index</h1>
			</div><!-- /.col -->

			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}">Users</a></li>
						<li class="breadcrumb-item active">Index</li>
				</ol>
			</div><!-- /.col -->
	</div><!-- /.row -->
	<hr>
@endsection

@section('content')
	<div class="content">
		<div class="container-fluid">
			
			<h3 class="mb-3">List of Users</h3>

			<table id="dataTable" class="table table-striped table-bordered">
				<thead>
					<tr class="text-center">
						<th>ID</th>
						<th>Avatar</th>
						<th>Last Name</th>
						<th>First Name</th>
						<th>Email</th>
						<th>Action</th>
					</tr>
				</thead>

				<tbody>
					@foreach ($users as $user)
						<tr class="text-center">
							<td>{{ $user->renderId() }}</td>
							<td><img src="{{ $user->renderDisplayImage() }}" alt="Admin Image" width="50px" height="50px"></td>
							<td>{{ $user->renderLastName() }}</td>
							<td>{{ $user->renderFirstName() }}</td>
							<td>{{ $user->renderEmail() }}</td>
							<td class="d-flex justify-content-center">
								<a href="{{ route('admin.users.show', $user->id) }}" class="btn btn-primary mx-1">
									<i class="fas fa-eye"></i>
								</a>
								<a href="{{ route('admin.users.edit', $user->id) }}" class="btn btn-primary mx-1">
									<i class="fas fa-edit"></i>
								</a>

								<form class="deleteItem mx-1" action="{{ route('admin.users.destroy', $user->id) }}" method="POST">
									@csrf
									{{ method_field('DELETE') }}

									<button class="btn btn-danger"><i class="fas fa-trash"></i></button>
								</form>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>
@endsection

resources/views/admin/pages/users/show.blade.php
@extends('admin.layouts.master')

@section('breadcrumb')
	<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark font-weight-bold">Show User</h1>
			</div><!-- /.col -->

			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}">Users</a></li>
						<li class="breadcrumb-item active">Show</li>
				</ol>
			</div><!-- /.col -->
	</div><!-- /.row -->
	<hr>
@endsection

@section('content')
	<div class="content">
		<div class="container-fluid">
			<div class="d-flex mb-3">
				<a href="{{ route('admin.users.show', $user->id) }}" class="btn btn-primary mr-1">
					<i class="fas fa-edit"></i>
					Edit
				</a>
		        <div>
		            <form class="deleteItem" action="{{ route('admin.users.destroy', $user->id) }}" method="POST">
		            	@csrf
		            	{{ method_field('DELETE') }}

		            	<button class="btn btn-danger"><i class="fas fa-trash mr-1"></i>Delete</button>
		            </form>
		        </div>
		    </div>

		    <div class="row">
		        <div class="col-md-12">
		            <div class="box">
		                <div class="box-header mb-3">
		                    <h3 class="box-title">User Details</h3>
		                </div>

		                <div class="box-body">
		                    <div class="row">
		                    	<div class="form-group col-md-6">
		                            <label for="email">ID</label>
		                            <p>{{ $user->renderId() }}</p>
		                        </div>

		                        <div class="form-group col-md-6">
		                            <label for="email">Email</label>
		                            <p>{{ $user->renderEmail() }}</p>
		                        </div>

		                        <div class="form-group col-md-6">
		                            <label for="lastName">Last Name</label>
		                            <p>{{ $user->renderLastName() }}</p>
		                        </div>

		                        <div class="form-group col-md-6">
		                            <label for="firstName">First Name</label>
		                            <p>{{ $user->renderFirstName() }}</p>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </div>
		    </div>
		</div>
	</div>
@endsection