routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function() {

	Route::namespace('Auth')->middleware('guest:admin')->group(function() {
		Route::get('login', 'LoginController@showLoginForm')->name('login');
		Route::post('login', 'LoginController@login')->name('login');

	});

	Route::middleware('auth:admin')->group(function() {
		Route::get('', 'DashboardController@index')->name('dashboard');

		Route::namespace('Auth')->group(function() {
			Route::get('logout', 'LoginController@logout')->name('logout');
		});

		Route::namespace('Admins')->group(function() {
			Route::get('admin', 'AdminController@index')->name('admins.index');
			Route::get('admin/{id}', 'AdminController@show')->name('admins.show');
			Route::get('admin/{id}/edit', 'AdminController@edit')->name('admins.edit');
			Route::post('admin/{id}', 'AdminController@update')->name('admins.update');
			Route::delete('admin/{id}', 'AdminController@destroy')->name('admins.destroy');
		});

		Route::namespace('Users')->group(function() {
			Route::get('users', 'UserController@index')->name('users.index');
			Route::get('user/{id}', 'UserController@show')->name('users.show');
			Route::get('user/{id}/edit', 'UserController@edit')->name('users.edit');
			Route::post('user/{id}', 'UserController@update')->name('users.update');
			Route::delete('user/{id}', 'UserController@destroy')->name('users.destroy');
		});

		Route::namespace('ActivityLogs')->group(function() {
			Route::get('activity_logs', 'ActivityLogController@index')->name('activity_logs.index');
		});
	});


});

resources/views/admin/partials/content.blade.php
<div class="content">
	<div class="content-header">
      	<div class="container-fluid">
        	@yield('breadcrumb')
      	</div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <div class="container-fluid">
        @yield('content')
    </div>
</div>

resources/views/admin/partials/footer.blade.php
<footer class="main-footer">
	<!-- To the right -->
	<div class="float-right d-none d-sm-inline">
		<a href="https://michaelgeofreydelarama.com">michaelgeofreydelarama.com</a>
	</div>
	<!-- Default to the left -->

	<p>Copyright &copy; 2019.  All rights reserved.</p>
</footer>

resources/views/admin/partials/head.blade.php
<head>
  	<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<meta http-equiv="x-ua-compatible" content="ie=edge">
  	<title>{{ config('app.name') }}</title>
  	<link rel="stylesheet" href="{{ asset('css/app.css') }}">
  	<!-- Data Table CSS -->
  	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
</head>

resources/views/admin/partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        @auth('admin')
            <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.logout') }}">
                    <img class="img-circle mr-1" src="{{ Auth::user()->renderDisplayImage() }}" width="30px" height="30px" alt="Me">
                    {{ Auth::user()->renderFullName() }} <span class="font-weight-bold">(Logout)</span>
                </a>
            </li>
        @endauth
    </ul>
</nav>

resources/views/admin/partials/scripts.blade.php
<!-- jQuery -->
<script src="{{ asset('js/jquery.min.js') }}"></script>

<!-- Bootstrap 4 -->
<script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>

<!-- AdminLTE App -->
<script src="{{ asset('js/adminlte.min.js') }}"></script>

<!-- Data Table -->
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>

<!-- Data Table Call -->
<script>
	$(document).ready( function () {
	    $('#dataTable').DataTable();
	} );	
</script>

<!-- Sweet Alert 2 -->
{{-- <script src="sweetalert2.all.min.js"></script> --}}

<script>
    $(".deleteItem").on("submit", function(){
        return confirm("Are you sure?");
    });
</script>

resources/views/admin/partials/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="/storage/cms_logo.png" alt="CMS Logo" class="brand-image img-circle elevation-3">
      <span class="brand-text font-weight-light">{{ config('app.name') }}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                <!-- Dashboard -->
                <li class="nav-item">
                    <a href="{{ route('admin.dashboard') }}" class="nav-link active">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Dashboard</p>
                    </a>
                </li>

                <!-- Models -->
                <li class="nav-item has-treeview menu-open">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-database"></i>
                        <p>
                            Models
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>

                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Sample Model 1</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Sample Model 2</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <!-- Content Management -->
                <li class="nav-item has-treeview menu-open">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-align-justify"></i>
                        <p>
                            Content Management
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>

                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Page</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Page Item</p>
                            </a>
                        </li>
                    </ul>
                </li>
                
                <!-- User Management -->
                <li class="nav-item">
                    <a href="{{ route('admin.users.index') }}" class="nav-link active">
                        <i class="nav-icon fas fa-users"></i>
                        <p>User Management</p>
                    </a>
                </li>

                <!-- Admin Management -->
                <li class="nav-item has-treeview menu-open">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-users-cog"></i>
                        <p>
                            Admin Management
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>

                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('admin.admins.index') }}" class="nav-link">
                                <i class="nav-icon fas fa-user-cog"></i>
                                <p>Admins</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-user-edit"></i>
                                <p>Roles</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-shield-alt"></i>
                                <p>Permissions</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <!-- Activity Logs -->
                <li class="nav-item">
                    <a href="{{ route('admin.activity_logs.index') }}" class="nav-link active">
                        <i class="nav-icon fas fa-list"></i>
                        <p>Activity Logs</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>